### ISSUE TITLE
I can't connect my wallet, sir.

### ISSUE THREAD

**Issue by saullfeng** [Jerga99/nft-marketplace#1]
![image](https://user-images.githubusercontent.com/55079495/191010461-610c1443-4274-4f80-9550-f0ce53851ae9.png)

**Comment by Jerga99** [comment]
Heya! (:

Did you follow the steps from Readme?  To create **.env.local** file and so on?

It's a course project, so to get it working properly done you need to follow the steps in Readme or watch the lectures.

Cheer (;
Filip

**Comment by saullfeng** [comment]
> Heya! (:
> 
> Did you follow the steps from Readme? To create **.env.local** file and so on?
> 
> It's a course project, so to get it working properly done you need to follow the steps in Readme or watch the lectures.
> 
> Cheer (; Filip

yes ，I have these environment configs and I just want to connect my wallet but he doesn't work

**Comment by Igor-Koniukhov** [comment]
In my case, that problem was caused due to mismatched networkId's. Try to check networkid in .env in ganache and in MetaMask (custom network) should be the same (1337 for example)

**Comment by saullfeng** [comment]
> In my case, that problem was caused due to mismatched networkId's. Try to check networkid in .env in ganache and in MetaMask (custom network) should be the same (1337 for example)

Thanks for your answer, he was really helpful. I removed the suffix .development from the configuration file and it worked

**Comment by saullfeng** [comment]
> > In my case, that problem was caused due to mismatched networkId's. Try to check networkid in .env in ganache and in MetaMask (custom network) should be the same (1337 for example)
> 
> Thanks for your answer, he was really helpful. I removed the suffix .development from the configuration file and it worked

I think it's just a vcode plugin issue, maybe I have too many plugins
