### ISSUE TITLE
Truffle Migrate Issue

### ISSUE THREAD

**Issue by mafzaldev** [Jerga99/nft-marketplace#2]
Truffle is unable to migrate contracts to Ganache due to some changes in OpenZeppelin contracts, which you can see in the attached link:

Add a fourth field in the _beforeTokenTransfer function and it will be fixed hopefully.

[Change Logs](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7c5f6bc2c8743d83443fa46395d75f2f3f99054a/CHANGELOG.md#breaking-changes)

**Comment by asolerp** [comment]
I've just added the missing field and it works as expected

```  
function _beforeTokenTransfer(
    address from,
    address to,
    uint tokenId,
    uint256 batchSize
  ) internal virtual override {
    super._beforeTokenTransfer(from, to, tokenId, batchSize);
        if (from == address(0)) {
          _addTOkenToAllTOkensEnumarion(tokenId);
        }
  }
